cluster/integration
FLira2000/supercon pull request #3
Opened 2020-06-28 23:34 UTC by FLira2000

2020-06-28 23:53 UTC, megazordcarioca requested changes
@FLira2000 Dá uma incluída no “.gitignore” o settings.json senão ele vai enviar tuas configs pessoais pro cluster. Fora isso, tudo certo. 
![image](https://user-images.githubusercontent.com/18271942/85961511-481cfb00-b981-11ea-9b61-fddac8becf3d.jpeg]

2020-06-28 23:53 UTC, megazordcarioca commented
> @FLira2000 Dá uma incluída no “.gitignore” o settings.json senão ele vai enviar tuas configs pessoais pro cluster. Fora isso, tudo certo. 
> ![image](https://user-images.githubusercontent.com/18271942/85961511-481cfb00-b981-11ea-9b61-fddac8becf3d.jpeg]

Esse github ainda buga pra enviar imagem

2020-06-29 00:01 UTC, FLira2000 commented
ve se ta bom ai agora
entendo nada de gitignore

2020-06-29 00:01 UTC, megazordcarioca approved these changes
Agora ta tudo certo

2020-06-29 00:02 UTC, merged